project:
  type: website
website:
  title: Araignées d'Île-de-France
  favicon: www/favicon.png
  reader-mode: false
  navbar:
    left:
    - href: index.qmd
      text: Accueil
    - href: about.qmd
      text: A propos
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
